// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTvU0VokE25SEmWaZiwuMbV1ZDYcVYSc',
    appId: '1:874877147347:web:67ea4c633e1dfa526edc26',
    messagingSenderId: '874877147347',
    projectId: 'chat-app-cf00d',
    authDomain: 'chat-app-cf00d.firebaseapp.com',
    storageBucket: 'chat-app-cf00d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDueAxhDfImUGmDZJCA93xZNN5kfeIAXlo',
    appId: '1:874877147347:android:8f7a9041a08f8c946edc26',
    messagingSenderId: '874877147347',
    projectId: 'chat-app-cf00d',
    storageBucket: 'chat-app-cf00d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPuq7yyNnG2yC0jARBJot117Gml5IT_ig',
    appId: '1:874877147347:ios:0c63456f0344a12d6edc26',
    messagingSenderId: '874877147347',
    projectId: 'chat-app-cf00d',
    storageBucket: 'chat-app-cf00d.appspot.com',
    iosClientId: '874877147347-hkihe1qi0q138vmvbats2r4gagmti3ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
